var weiUrls={
    "oauth2":{
        "host":"api.weibo.com",
        "path":"/oauth2/",
        "protocol":"https://"
    },
    "messages":{
        "host":"m.api.weibo.com",
        "path":"/2/messages/",
        "protocol":"https://"
    },
    "statuses":{
        "host":"api.weibo.com",
        "path":"/2/statuses/",
        "protocol":"https://"
    },
    "comments":{
        "host":"api.weibo.com",
        "path":"/2/comments/",
        "protocol":"https://"
    },
    "users":{
        "host":"api.weibo.com",
        "path":"/2/users/",
        "protocol":"https://"
    },
    "trends":{
        "host":"api.weibo.com",
        "path":"/2/trends/",
        "protocol":"https://"
    },
    "friendships":{
        "host":"api.weibo.com",
        "path":"/2/friendships/",
        "protocol":"https://"
    },
    "account":{
        "host":"api.weibo.com",
        "path":"/2/account/",
        "protocol":"https://"
    },
    "favorites":{
        "host":"api.weibo.com",
        "path":"/2/favorites/",
        "protocol":"https://"
    },
    "tags":{
        "host":"api.weibo.com",
        "path":"/2/tags/",
        "protocol":"https://"
    },
    "register":{
        "host":"api.weibo.com",
        "path":"/2/register/",
        "protocol":"https://"
    },
    "search":{
        "host":"api.weibo.com",
        "path":"/2/search/",
        "protocol":"https://"
    },
    "suggestions":{
        "host":"api.weibo.com",
        "path":"/2/suggestions/",
        "protocol":"https://"
    },
    "remind":{
        "host":"api.weibo.com",
        "path":"/2/remind/",
        "protocol":"https://"
    },
    "short_url":{
        "host":"api.weibo.com",
        "path":"/2/short_url/",
        "protocol":"https://"
    },
    "notification":{
        "host":"api.weibo.com",
        "path":"/2/notification/",
        "protocol":"https://"
    },
    "common":{
        "host":"api.weibo.com",
        "path":"/2/common/",
        "protocol":"https://"
    },
    "location":{
        "host":"api.weibo.com",
        "path":"/2/location/",
        "protocol":"https://"
    }
};

exports.weiUrls=weiUrls;

